---

dist: focal
language: python
python: "3.9"
os: linux
services:
  - docker
install:
  - pip install pipenv==2022.10.12
  - pipenv sync
env:
  matrix:
    - MOLECULE_DISTRO=debian:bullseye-slim
    - MOLECULE_DISTRO=debian:buster-slim
    - MOLECULE_DISTRO=debian:stretch-slim
script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
