---

- name: NGINX | Dependencies
  import_tasks: dependencies.yml
  when:
    - nginx_prometheus_metrics_enabled
    - nginx_luajit_version is defined
  tags:
    - nginx-dependencies

- name: NGINX | Install
  import_tasks: install.yml
  tags:
    - nginx-install

- name: NGINX | Configure
  import_tasks: config.yml
  tags:
    - nginx-configure

- name: NGINX | Metrics
  import_tasks: metrics.yml
  when: nginx_prometheus_metrics_enabled
  tags:
    - nginx-metrics

- name: NGINX | Service
  import_tasks: service.yml
  tags:
    - nginx-service
